name: CI
on:
  push:
    # branches:
    #   - main
    # tags: ['*']
    paths-ignore:
      - 'NEWS.md'
      - 'README.md'
      - 'LICENSE.md'
      - 'benchmark/**'
  pull_request:
    paths-ignore:
      - 'NEWS.md'
      - 'README.md'
      - 'LICENSE.md'
      - 'benchmark/**'
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  test-sequential:
    name: ${{ matrix.testcase }} - Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.10'
        os:
          - ubuntu-latest
        arch:
          - x64
        testcase:
          - seq-atlas-discrete-models
          - seq-l2-projection
          - seq-laplacian
          - seq-geophysical
          - seq-transient
          - seq-geometry
          - seq-multigrid
          - seq-tutorials
          - seq-fields
          - seq-ambient-model
          - seq-autodiff
          - seq-benchmark
    steps:
      - uses: actions/checkout@v6
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        env:
          TESTCASE: ${{ matrix.testcase }}
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v5
        with:
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
  #         flags: ${{ matrix.testcase }}